---
title: "Apply CRM - PNW states"
author: "Matt Russell"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(knitr)
library(readxl)
```

```{r}
# Set working directory
my_dir <-".../crm_eqns/"
```

```{r}
# Load volume functions
source(purl(paste0(my_dir, "volume/volume_pnw.Rmd"), quiet = T))

# Load CRM functions
source(purl(paste0(my_dir, "crm/crm.Rmd"), quiet = T))
```


```{r}
# Gross volume

# coefficients files
read_coefs <- function(sheet_name){
  read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = sheet_name) |> 
      rename(COEF_TBL_SP = Species) |> 
    mutate(COEF_TABLE = sheet_name)|> 
    relocate(COEF_TABLE, COEF_TBL_SP)
}

relocate_order <- c("COEF_TABLE", "COEF_TBL_SP", "B0", "B1", "B2", "B3", "B4", "B5", 
           "B6", "B7", "B8", "B9", "B10", "B11", "B12",
           "B13", "B14", "B15", "B16", "B17", "B18", "B19",
           "B20", "B21", "B22", "B23", "B24", "B25", "B26") 

coefs_PNW_1 <- read_coefs(sheet_name = "PNW_coefs_1") |> 
  mutate(B0 = NA, B4 = NA, B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_2 <- read_coefs(sheet_name = "PNW_coefs_2") |> 
    mutate(B0 = NA, B12 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_3 <- read_coefs(sheet_name = "PNW_coefs_3") |> 
      mutate(B0 = NA, B12 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_4 <- read_coefs(sheet_name = "PNW_coefs_4") |> 
        mutate(B0 = NA, B12 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order)  

coefs_PNW_5 <- read_coefs(sheet_name = "PNW_coefs_5") |> 
        mutate(B0 = 0, B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order)  

coefs_PNW_6 <- read_coefs(sheet_name = "PNW_coefs_6") |> 
  mutate(B0 = NA, B4 = NA,  B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_7 <- read_coefs(sheet_name = "PNW_coefs_7") |> 
  mutate(B0 = NA, B4 = NA,  B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_8 <- read_coefs(sheet_name = "PNW_coefs_8")  |> 
  mutate(B0 = NA, B4 = 0,  B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order)  

coefs_PNW_9 <- read_coefs(sheet_name = "PNW_coefs_9") |> 
  mutate(B0 = NA, B4 = 0,  B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_10 <- read_coefs(sheet_name = "PNW_coefs_10")  |> 
  mutate(B0 = NA, B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order)  

coefs_PNW_11 <- read_coefs(sheet_name = "PNW_coefs_11") |> 
   mutate(B0 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_12 <- read_coefs(sheet_name = "PNW_coefs_12") |> 
   mutate(B0 = NA, B12 = 0, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_13 <- read_coefs(sheet_name = "PNW_coefs_13") |> 
   mutate(B0 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_14 <- read_coefs(sheet_name = "PNW_coefs_14") |> 
   mutate(B0 = NA, B10 = 0, B11 = 0, B12 = 0, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_15 <- read_coefs(sheet_name = "PNW_coefs_15") |> 
   mutate(B0 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_16 <- read_coefs(sheet_name = "PNW_coefs_16") |> 
   mutate(B0 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_17 <- read_coefs(sheet_name = "PNW_coefs_17") |> 
   mutate(B9 = 0, B10 = 0, B11 = 0, B12 = NA, B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_21 <- read_coefs(sheet_name = "PNW_coefs_21") |> 
  mutate(B0 = NA,  B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_RMRS_5 <- read_coefs(sheet_name = "RMRS_coefs_5") |> 
  mutate(B0 = NA,  B4 = 0, B5 = 0, B6 = 0, B7 = 0, B8 = 0, B9 = 0, B10 = 0,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_RMRS_6 <- read_coefs(sheet_name = "RMRS_coefs_6") |> 
  filter(`# of stems` == 1) |> 
  select(-`# of stems`) |>
  mutate(B0 = NA, B7 = 0, B8 = 0, B9 = 0, B10 = 0,
         B11 = NA, B12 = NA,  B13 = NA, B14 = NA, B15 = NA, B16 = NA,
         B17 = NA, B18 = NA, B19 = NA, B20 = NA, B21 = NA, B22 = NA,
         B23 = NA, B24 = NA, B25 = NA, B26 = NA) |> 
  relocate(relocate_order) 

coefs_PNW_sp <- rbind(coefs_PNW_1, coefs_PNW_2, coefs_PNW_3, coefs_PNW_4,
                    coefs_PNW_15, coefs_PNW_17, coefs_PNW_21, coefs_RMRS_5, coefs_RMRS_6)
```


```{r}
# Config files
read_config <- function(sheet_name){
  read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = sheet_name) |> 
    rename(SPCD = SPECIES_NUM)
}

config_CA <- read_config(sheet_name = "CA_config") 
config_CA_MC <- read_config(sheet_name = "CA_MC_config") 
config_OR_E <- read_config(sheet_name = "OR_E_config") 
config_OR_W <- read_config(sheet_name = "OR_W_config") 
config_OR_JJ <- read_config(sheet_name = "OR_JJ_config") 
config_WA_E <- read_config(sheet_name = "WA_E_config") 
config_WA_W <- read_config(sheet_name = "WA_W_config") 
config_WA_CF <- read_config(sheet_name = "WA_CF_config")

######################################
# Join coefficients and config files

create_coefs_all <- function(coefs){
      coefs |> 
    mutate(state = NA,
             region = NA,
             COEF_TBL_SP  = as.numeric(ifelse(COEF_TBL_SP == "All", NA, NA)),
             SPCD = NA) |>
  relocate(state, region, COEF_TABLE, COEF_TBL_SP, SPCD)
}

sp_coefs_5 <- create_coefs_all(coefs = coefs_PNW_5)
sp_coefs_6 <- create_coefs_all(coefs = coefs_PNW_6)
sp_coefs_7 <- create_coefs_all(coefs = coefs_PNW_7)
sp_coefs_8 <- create_coefs_all(coefs = coefs_PNW_8)
sp_coefs_9 <- create_coefs_all(coefs = coefs_PNW_9)
sp_coefs_10 <- create_coefs_all(coefs = coefs_PNW_10)
sp_coefs_11 <- create_coefs_all(coefs = coefs_PNW_11)
sp_coefs_12 <- create_coefs_all(coefs = coefs_PNW_12)
sp_coefs_13 <- create_coefs_all(coefs = coefs_PNW_13)
sp_coefs_14 <- create_coefs_all(coefs = coefs_PNW_14)
sp_coefs_16 <- create_coefs_all(coefs = coefs_PNW_16)

pnw_sp <- read_excel(paste0(my_dir, "pnw_crm_species.xlsx"))
```

```{r}
sp_coefs_5 <- as_tibble(cbind(pnw_sp, sp_coefs_5[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_5")
sp_coefs_6 <- as_tibble(cbind(pnw_sp, sp_coefs_6[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_6")
sp_coefs_7 <- as_tibble(cbind(pnw_sp, sp_coefs_7[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_7")
sp_coefs_8 <- as_tibble(cbind(pnw_sp, sp_coefs_8[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_8")
sp_coefs_9 <- as_tibble(cbind(pnw_sp, sp_coefs_9[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_9")
sp_coefs_10 <- as_tibble(cbind(pnw_sp, sp_coefs_10[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_10")
sp_coefs_11 <- as_tibble(cbind(pnw_sp, sp_coefs_11[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_11")
sp_coefs_12 <- as_tibble(cbind(pnw_sp, sp_coefs_12[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_12")
sp_coefs_13 <- as_tibble(cbind(pnw_sp, sp_coefs_13[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_13")
sp_coefs_14 <- as_tibble(cbind(pnw_sp, sp_coefs_14[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_14")
sp_coefs_16 <- as_tibble(cbind(pnw_sp, sp_coefs_16[1, 6:32])) |> 
  filter(COEF_TABLE == "PNW_coefs_16")

sp_coefs_all <- rbind(sp_coefs_5, sp_coefs_6, sp_coefs_7, sp_coefs_8, 
                      sp_coefs_9, sp_coefs_10, sp_coefs_11, sp_coefs_12, 
                      sp_coefs_13, sp_coefs_14, sp_coefs_16)
```

```{r}
join_coefs <- function(coefs, config, state, region){
  inner_join(coefs, config, by = c("COEF_TABLE", "COEF_TBL_SP")) |> 
      mutate(state = state,
             region = region) |>
  relocate(state, region, COEF_TABLE, COEF_TBL_SP, SPCD)
}

# California - state
sp_CA_state <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_CA,
                          state = "CA",
                          region = "state") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "CA" & region == "state")

sp_CA_state

# California - mixed-conifers
sp_CA_mc <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_CA_MC,
                          state = "CA",
                          region = "mc") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "CA" & region == "mc")

sp_CA_mc


# Oregon - east
sp_OR_east <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_OR_E,
                          state = "OR",
                          region = "east") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "OR" & region == "east")

sp_OR_east


# Oregon - west
sp_OR_west <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_OR_W,
                          state = "OR",
                          region = "west") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "OR" & region == "west")

sp_OR_west


# Oregon - Jackson and Josephine Counties, OR
sp_OR_jj <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_OR_JJ,
                          state = "OR",
                          region = "jj") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "OR" & region == "jj")

sp_OR_jj


# Washington - east
sp_WA_east <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_WA_E,
                          state = "WA",
                          region = "east") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "WA" & region == "east")

sp_WA_east


# Washington - west
sp_WA_west <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_WA_W,
                          state = "WA",
                          region = "west") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "WA" & region == "west")

sp_WA_west


# Washington - CF counties
sp_WA_cf <- join_coefs(coefs = coefs_PNW_sp,
                          config = config_WA_CF,
                          state = "WA",
                          region = "cf") |>
  select(state:B26) |>
  rbind(sp_coefs_all) |> 
  filter(state == "WA" & region == "cf")

sp_WA_cf

sp_all <- rbind(sp_CA_state, sp_CA_mc, 
                sp_OR_east, sp_OR_west, sp_OR_jj, 
                sp_WA_east, sp_WA_west, sp_WA_cf)
```

```{r}
# tree <- tribble(
#   ~state, ~region, ~SPCD, ~DIA, ~HT,
#   "CA", "state", 202, 5.2, 42,
#   "CA", "mc", 202, 5.2, 42,
#   "OR", "east", 202, 5.2, 42,
#   "OR", "west", 202, 5.2, 42,
#   "OR", "jj", 202, 5.2, 42,
#   "WA", "east", 202, 5.2, 42,
#   "WA", "west", 202, 5.2, 42,
#   "WA", "cf", 202, 5.2, 42,
#   ) |>
#   inner_join(sp_all, by = c("state", "region", "SPCD"))
```

```{r}
tree <- sdt_tree 
table(tree$VOL_LOC_GRP)
# tree <- tree |> 
#   mutate(state = toupper(state),
#         eco_province = str_sub(ECOSUBCD, end = -3),
#         eco_division = str_replace(eco_province, ".$", "0"))

# eco_div <- read_excel(paste0(my_dir, "pnw_ecoregion_key.xlsx"))

volume_key <- read_excel(paste0(my_dir, "pnw_volume_key.xlsx"))

tree <- tree |> 
  mutate(state = toupper(state),
        eco_province = str_sub(ECOSUBCD, end = -3),
        eco_division = str_replace(eco_province, ".$", "0")) |> 
 inner_join(volume_key, by = c("state", "VOL_LOC_GRP"))
```

```{r}
tree <- tree |> 
  mutate(SPCD = ifelse(state == "WA" & region == "west" & SPCD %in% c(212, 927), 999, SPCD),
         SPCD = ifelse(state == "OR" & region == "west" & SPCD == 771, 999, SPCD)) |> 
  left_join(sp_all, by = c("state", "region", "SPCD"))

tree_eg <- tree |> 
   select(state, region, SPCD, COEF_TABLE)

tree <- tree |> 
  mutate(VOLCFGRS = ifelse(COEF_TABLE == "PNW_coefs_1", 
                           calc_VOLCFGRS_pills_kirk(SPCD = SPCD, DBH = DIA, HT = HT,
                                     B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE %in% c("PNW_coefs_2", "PNW_coefs_3"), 
                           calc_VOLCFGRS_brackett_browne_1(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5, 
                                       B6 = B6, B7 = B7, B8 = B8, B9 = B9, B10 = B10, 
                                       B11 = B11),
                    ifelse(COEF_TABLE == "PNW_coefs_4", 
                           calc_VOLCFGRS_brack_krum_browne(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5, 
                                       B6 = B6, B7 = B7, B8 = B8, B9 = B9, B10 = B10, B11 = B11),
                    ifelse(COEF_TABLE == "PNW_coefs_5", 
                           calc_VOLCFGRS_mac_berg_2(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B0 = B0, B1 = B1, B2 = B2, B3 = B3, B4 = B4), 
                    ifelse(COEF_TABLE == "PNW_coefs_6", 
                           calc_VOLCFGRS_mac_berg_1(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "PNW_coefs_7", 
                           calc_VOLCFGRS_mac_berg_3(SPCD = SPCD, DBH = DIA, HT = HT, 
                                                     B0 = B0, B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "PNW_coefs_8", 
                           calc_VOLCFGRS_mac_berg_4(SPCD = SPCD, DBH = DIA, HT = HT, 
                                                     B1 = B1, B2 = B2, B3 = B3),
                    ifelse(COEF_TABLE == "PNW_coefs_9", 
                           calc_VOLCFGRS_brack_mac_berg(SPCD = SPCD, DBH = DIA, HT = HT, 
                                                     B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "PNW_coefs_10", 
                           calc_VOLCFGRS_mac_berg_5(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4),
                    ifelse(COEF_TABLE == "PNW_coefs_11", 
                           calc_VOLCFGRS_brack_cham_browne(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12), 
                    ifelse(COEF_TABLE == "PNW_coefs_12", 
                           calc_VOLCFGRS_brack_browne_bell(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11), 
                    ifelse(COEF_TABLE == "PNW_coefs_13", 
                           calc_VOLCFGRS_brack_curt_browne(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12, B13 = B13, 
                                       B14 = B14, B15 = B15, B16 = B16, B17 = B17, 
                                       B18 = B18, B19 = B19, B20 = B20, B21 = B21,
                                       B22 = B22, B23 = B23, B24 = B24, B25 = B25, B26 = B26), 
                    ifelse(COEF_TABLE == "PNW_coefs_14", 
                           calc_VOLCFGRS_brack_mac_browne(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9), 
                   ifelse(COEF_TABLE == "PNW_coefs_15", 
                           calc_VOLCFGRS_brack_summ_browne(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12, B13 = B13), 
                    ifelse(COEF_TABLE == "PNW_coefs_16", 
                           calc_VOLCFGRS_brack_browne_2(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12, B13 = B13, B14 = B14), 
                    ifelse(COEF_TABLE == "RMRS_coefs_5", 
                           calc_VOLCFGRS_chojnacky85(SPCD = SPCD, DRC = DIA, HT = HT, NUM_STEMS = 1, 
                                                     B0 = B0, B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "RMRS_coefs_6", 
                           calc_VOLCFGRS_chojnacky88(SPCD = SPCD, DRC = DIA, HT = HT, 
                                                     B1 = B1, B2 = B2, B3 = B3,
                                                     B4 = B4, B5 = B5, B6 = B6),
                    ifelse(COEF_TABLE == "PNW_coefs_21", 
                           calc_VOLCFGRS_brack_chitt_mac(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B0 = B0, B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10), 999))))))))))))))))))) 
```

```{r}
# Reference Species table
ref_spp <- read_csv(paste0(my_dir, "nrs_gtr88/REF_SPECIES.csv")) 

# Domke et al. 2011 Standing dead reductions (their Table 2)
dead <- tribble(
 ~SFTWD_HRDWD, ~DECAYCD, ~DENS_RED, ~SLA_TOP, ~SLA_BARK, ~SLA_BOLE, ~SLA_STUMP, ~SLA_ROOTS,
 # Hardwoods
 "H", 0, 1, 1, 1, 1, 1, 1,
 "H", 1, 0.970, 1, 0.92, 1, 1, 1, 
 "H", 2, 0.750, 0.50, 0.66, 1, 1, 0.95,
 "H", 3, 0.540, 0.20, 0.39, 1, 1, 0.80,
 "H", 4, 0.613, 0.10, 0.21, 1, 1, 0.65,
 "H", 5, 0.613, 0, 0, 1, 1, 0.50,
 # Softwoods
 "S", 0, 1, 1, 1, 1, 1, 1,
 "S", 1, 0.892, 1, 0.92, 1, 1, 1,
 "S", 2, 0.831, 0.50, 0.66, 1, 1, 0.95,
 "S", 3, 0.591, 0.20, 0.39, 1, 1, 0.80,
 "S", 4, 0.433, 0.10, 0.21, 1, 1, 0.65,
 "S", 5, 0.433, 0, 0, 1, 1, 0.50
 )
```

```{r}
# Sound volume
tree <- tree |> 
  rowwise() |> 
  mutate(VOLCFSND = calc_VOLCFSND(VOLCFGRS = VOLCFGRS, PCT_ROTTEN = CULL)) 
tree$VOLCFGRS
tree$VOLCFSND
```

```{r}
tree <- inner_join(tree, ref_spp, by = "SPCD") 

tree <- inner_join(tree, dead, by = c("SFTWD_HRDWD", "DECAYCD")) |> 
  select(-c(HABTYPCD1, HABTYPCD2))

tree <- tree |> 
  rowwise() |> 
  # 3. DRYBIO_BOLE
  mutate(DRYBIO_BOLE = calc_DRYBIO_BOLE(SPCD = SPCD, VOLCFSND = VOLCFSND, 
                                        WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                                        BARK_VOL_PCT = BARK_VOL_PCT,
                                        BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                                        DENS_RED = DENS_RED, 
                                        SLA_BOLE = SLA_BOLE, 
                                        SLA_BARK = SLA_BARK),
      # 4. CRM adjustment factor   
      CRM_AF = calc_CRM_ADJ(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                               DRYBIO_BOLE = DRYBIO_BOLE, 
                               DBH = DIA),
      # 5. Stump volume and biomass
      DRYBIO_STUMP = calc_DRYBIO_STUMP(SPCD = SPCD, 
                               DBH = DIA,
                               CRM_AF = CRM_AF,
                               RAILE_STUMP_DOB_B1 = RAILE_STUMP_DOB_B1, 
                               RAILE_STUMP_DIB_B1 = RAILE_STUMP_DIB_B1, 
                               RAILE_STUMP_DIB_B2 = RAILE_STUMP_DIB_B2,
                               WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                               BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                               SLA_STUMP = SLA_STUMP),
      # 6. Top and branch biomass
      DRYBIO_TOP = calc_TOP_BRANCH(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                                        DBH = DIA, 
                                        DRYBIO_STUMP = DRYBIO_STUMP, 
                                        DRYBIO_BOLE = DRYBIO_BOLE,
                                      SLA_TOP = SLA_TOP),
      # 7. Total aboveground biomass
      BIOMASS = calc_BIOMASS(DBH = DIA,
                             JENKINS_SPGRPCD =JENKINS_SPGRPCD,
                             DRYBIO_BOLE = DRYBIO_BOLE, 
                                DRYBIO_STUMP = DRYBIO_STUMP, 
                                DRYBIO_TOP = DRYBIO_TOP,
                             DENS_RED = DENS_RED, 
                             SLA_TOP = SLA_TOP, 
                             SLA_BOLE = SLA_BOLE, 
                             SLA_BARK = SLA_BARK),
      # 8. Total aboveground carbon
      CARBON = calc_CARBON(BIOMASS = BIOMASS)
      ) 

tree <- tree |> 
  mutate(CARBON = ifelse(is.nan(CARBON), 0, CARBON),
         BIOMASS = ifelse(is.nan(BIOMASS), 0, BIOMASS))

tree$VOLCFGRS
tree$VOLCFSND
tree$CRM_AF
tree$DRYBIO_BOLE
tree$DRYBIO_STUMP
tree$DRYBIO_TOP
tree$BIOMASS
tree$CARBON

tree_eg <- tree |> 
  select(state, region, SPCD, DIA, HT, STANDING_DEAD_CD, DECAYCD, CULL,
         COEF_TABLE, VOLCFGRS, VOLCFSND, CARBON)
```
