---
title: "Apply CRM - RMRS states"
author: "Matt Russell"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(knitr)
library(readxl)
```

```{r}
# Set working directory
my_dir <-".../crm_eqns/"
```

```{r}
# Load volume functions
source(purl(paste0(my_dir, "volume/volume_rmrs.Rmd"), quiet = T))

# Load CRM functions
source(purl(paste0(my_dir, "crm/crm.Rmd"), quiet = T))
```


```{r}
# Gross volume

# coefficients files
read_coefs <- function(sheet_name){
  read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = sheet_name) |> 
      rename(COEF_TBL_SP = Species) |> 
    mutate(COEF_TABLE = sheet_name)|> 
    relocate(COEF_TABLE, COEF_TBL_SP)
}

coefs_RMRS_1 <- read_coefs(sheet_name = "RMRS_coefs_1") |> 
  mutate(B0 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_2 <- read_coefs(sheet_name = "RMRS_coefs_2") |> 
    mutate(B0 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_3 <- read_coefs(sheet_name = "RMRS_coefs_3") |> 
      mutate(B4 = NA, B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_4 <- read_coefs(sheet_name = "RMRS_coefs_4") |> 
        mutate(B0 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_5 <- read_coefs(sheet_name = "RMRS_coefs_5") |> 
        mutate(B4 = NA, B5 = NA, B6 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_6 <- read_coefs(sheet_name = "RMRS_coefs_6") |> 
  filter(`# of stems` == 1) |> 
  select(-`# of stems`) |>
  mutate(B0 = NA, B7 = NA, B8 = NA, B9 = NA, B10 = NA,
         B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_7 <- read_coefs(sheet_name = "RMRS_coefs_7") |> 
  mutate(B0 = NA, B8 = NA, B9 = NA, B10 = NA,
           B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_8 <- read_coefs(sheet_name = "RMRS_coefs_8")  |> 
  mutate(B0 = NA, B7 = 0, B8 = NA, B9 = NA, B10 = NA,
           B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_9 <- read_coefs(sheet_name = "RMRS_coefs_9") |> 
    mutate(B0 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_10 <- read_coefs(sheet_name = "RMRS_coefs_10")  |> 
  mutate(B0 = NA, B6 = NA, B7 = 0, B8 = NA, B9 = NA, B10 = NA,
           B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS_11 <- read_coefs(sheet_name = "RMRS_coefs_11") |> 
  mutate(B2 = NA, B3 = NA, B4 = NA, B5 = NA, B6 = NA, B7 = 0, B8 = NA, B9 = NA, B10 = NA,
           B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_PNW_21 <- read_coefs(sheet_name = "PNW_coefs_21") |> 
    mutate(B0 = NA, B11 = NA, B12 = NA) |> 
  relocate(COEF_TABLE, COEF_TBL_SP, B0, B1, B2, B3, B4, B5, 
           B6, B7, B8, B9, B10, B11, B12) 

coefs_RMRS <- rbind(coefs_RMRS_1, coefs_RMRS_2, coefs_RMRS_3, coefs_RMRS_4,
                    coefs_RMRS_5, coefs_RMRS_6, coefs_RMRS_7, coefs_RMRS_8,
                    coefs_RMRS_9, coefs_RMRS_10, coefs_RMRS_11, coefs_PNW_21)
###################################

# Config files
read_config <- function(sheet_name){
  read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = sheet_name) |> 
    rename( SPCD = SPECIES_NUM)
}

config_AZ_N_NM_N <- read_config(sheet_name = "AZ_N_NM_N_config") 
config_AZ_S_NM_S <- read_config(sheet_name = "AZ_S_NM_S_config") 
config_CO_E_WY_E <- read_config(sheet_name = "CO_E_WY_E_config") 
config_CO_W_WY_W <- read_config(sheet_name = "CO_W_WY_W_config") 
config_ID_MTW <- read_config(sheet_name = "ID_MTW_config") 
config_MT_E <- read_config(sheet_name = "MT_E_config") 
config_NV <- read_config(sheet_name = "NV_config") 
config_UT_NE <- read_config(sheet_name = "UT_NE_config") 
config_UT_SW <- read_config(sheet_name = "UT_SW_config")

######################################
# Join coefficients and config files

join_coefs <- function(coefs, config, state, region){
  inner_join(coefs, config, by = c("COEF_TABLE", "COEF_TBL_SP")) |> 
      mutate(state = state,
             region = region) |>
  relocate(state, region, COEF_TABLE, COEF_TBL_SP, SPCD)
}

# Arizona
sp_AZ_north <- join_coefs(coefs = coefs_RMRS,
                          config = config_AZ_N_NM_N,
                          state = "AZ",
                          region = "north")

sp_AZ_south <- join_coefs(coefs = coefs_RMRS,
                          config = config_AZ_S_NM_S,
                          state = "AZ",
                          region = "south")
# New Mexico

sp_NM_north <- join_coefs(coefs = coefs_RMRS,
                          config = config_AZ_N_NM_N,
                          state = "NM",
                          region = "north")

sp_NM_south <- join_coefs(coefs = coefs_RMRS,
                          config = config_AZ_S_NM_S,
                          state = "NM",
                          region = "south")

# Colorado
sp_CO_east <- join_coefs(coefs = coefs_RMRS,
                          config = config_CO_E_WY_E,
                          state = "CO",
                          region = "east")

sp_CO_west <- join_coefs(coefs = coefs_RMRS,
                          config = config_CO_W_WY_W,
                          state = "CO",
                          region = "west")

# Wyoming
sp_WY_east <- join_coefs(coefs = coefs_RMRS,
                          config = config_CO_E_WY_E,
                          state = "WY",
                          region = "east")

sp_WY_west <- join_coefs(coefs = coefs_RMRS,
                          config = config_CO_W_WY_W,
                          state = "WY",
                          region = "west")

# Montana
sp_MT_west <- join_coefs(coefs = coefs_RMRS,
                          config = config_ID_MTW,
                          state = "MT",
                          region = "west")

sp_MT_east <- join_coefs(coefs = coefs_RMRS,
                          config = config_MT_E,
                          state = "MT",
                          region = "east")

# Utah
sp_UT_northeast <- join_coefs(coefs = coefs_RMRS,
                          config = config_UT_NE,
                          state = "UT",
                          region = "northeast")

sp_UT_southwest <- join_coefs(coefs = coefs_RMRS,
                          config = config_UT_SW,
                          state = "UT",
                          region = "southwest")

# Idaho
sp_ID_all <- join_coefs(coefs = coefs_RMRS,
                          config = config_ID_MTW,
                          state = "ID",
                          region = "all")

# Nevada
sp_NV_all <- join_coefs(coefs = coefs_RMRS,
                          config = config_NV,
                          state = "NV",
                          region = "all")

sp_all <- rbind(sp_AZ_north, sp_AZ_south, sp_NM_north, sp_NM_south, 
                sp_CO_east, sp_CO_west, sp_WY_east, sp_WY_west, 
                sp_MT_west, sp_MT_east, sp_UT_northeast, sp_UT_southwest, 
                sp_ID_all, sp_NV_all)
```

```{r}
# tree <- tribble( 
#   ~state, ~region, ~SPCD, ~DIA, ~HT, 
#   "NM", "south", 242, 5.2, 42,
#   "AZ", "north", 15, 5.2, 42,
#   "AZ", "north", 134, 5.2, 42,
#   "AZ", "north", 51, 5.2, 42,
#   "AZ", "north", 133, 5.2, 42,
#   "AZ", "south", 322, 5.2, 42,
#   "AZ", "south", 117, 5.2, 42,
#   "AZ", "south", 202, 5.2, 42,
#   "AZ", "south", 51, 5.2, 42,
#   "CO", "east", 51, 5.2, 42,
#   "CO", "west", 51, 5.2, 42,
#   "ID", "all", 64, 5.2, 42
#   ) |> 
#   inner_join(sp_all, by = c("state", "region", "SPCD"))
```

```{r}
# # Write volume function
# calc_VOLCFGRS <- function(){  
#   if(COEF_TABLE == "RMRS_coefs_1"){
#     VOLCFGRS = calc_VOLCFGRS_unknown(SPCD = SPCD, DBH = DBH, HT = HT,
#                                      B1 = B1, B2 = B2, B3 = B3, B4 = B4)}
#   else if(COEF_TABLE == "RMRS_coefs_2"){ 
#     VOLCFGRS = calc_VOLCFGRS_hann_bare(SPCD = SPCD, DBH = DBH, HT = HT, 
#                                        B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5, B6 = B6)}
#   else{
#     VOLCFGRS <- 999
#   }
#   # Return the result
#   return(VOLCFGRS)
# }

tree <- sdt_tree 

eco_div <- read_excel(paste0(my_dir, "rmrs_ecoregion_key.xlsx"))

tree <- tree |> 
  mutate(state = toupper(state),
        eco_province = str_sub(ECOSUBCD, end = -3),
        eco_division = str_replace(eco_province, ".$", "0")) |> 
  inner_join(eco_div, by = c("state", "eco_division"))
```

```{r}
tree <- tree |> 
  inner_join(sp_all, by = c("state", "region", "SPCD"))

tree <- tree |> 
  mutate(VOLCFGRS = ifelse(COEF_TABLE == "RMRS_coefs_1", 
                           calc_VOLCFGRS_unknown(SPCD = SPCD, DBH = DIA, HT = HT,
                                     B1 = B1, B2 = B2, B3 = B3, B4 = B4), 
                    ifelse(COEF_TABLE == "RMRS_coefs_2", 
                           calc_VOLCFGRS_hann_bare(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5, B6 = B6),
                    ifelse(COEF_TABLE == "RMRS_coefs_3", 
                           calc_VOLCFGRS_chojnacky94(SPCD = SPCD, DRC = DIA, HT = HT, 
                                       B0 = B0, B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "RMRS_coefs_4", 
                           calc_VOLCFGRS_hann_bare_plus(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12), 
                    ifelse(COEF_TABLE == "RMRS_coefs_5", 
                           calc_VOLCFGRS_chojnacky85(SPCD = SPCD, DRC = DIA, HT = HT, NUM_STEMS = 1, 
                                                     B0 = B0, B1 = B1, B2 = B2, B3 = B3), 
                    ifelse(COEF_TABLE == "RMRS_coefs_6", 
                           calc_VOLCFGRS_chojnacky88(SPCD = SPCD, DRC = DIA, HT = HT, 
                                                     B1 = B1, B2 = B2, B3 = B3,
                                                     B4 = B4, B5 = B5, B6 = B6),
                    ifelse(COEF_TABLE == "RMRS_coefs_7", 
                           calc_VOLCFGRS_moisen(SPCD = SPCD, DBH = DIA, HT = HT, 
                                                     B1 = B1, B2 = B2, B3 = B3,
                                                     B4 = B4, B5 = B5, B6 = B6, B7 = B7), 
                    ifelse(COEF_TABLE == "RMRS_coefs_8", 
                           calc_VOLCFGRS_hann_bare(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5, B6 = B6), 
                    ifelse(COEF_TABLE == "RMRS_coefs_9", 
                           calc_VOLCFGRS_hann_bare_plus(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10, B11 = B11, B12 = B12), 
                    ifelse(COEF_TABLE == "RMRS_coefs_10", 
                           calc_VOLCFGRS_myers(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5),
                    ifelse(COEF_TABLE == "RMRS_coefs_11", 
                           calc_VOLCFGRS_edminster(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B0 = B0, B1 = B1), 
                    ifelse(COEF_TABLE == "PNW_coefs_21", 
                           calc_VOLCFGRS_chit_mac(SPCD = SPCD, DBH = DIA, HT = HT, 
                                       B0 = B0, B1 = B1, B2 = B2, B3 = B3, B4 = B4,
                                       B5 = B5, B6 = B6, B7 = B7, B8 = B8, B9 = B9,
                                       B10 = B10), 999))))))))))))) 
```

```{r}
# Reference Species table
ref_spp <- read_csv(paste0(my_dir, "nrs_gtr88/REF_SPECIES.csv")) 

# Domke et al. 2011 Standing dead reductions (their Table 2)
dead <- tribble(
 ~SFTWD_HRDWD, ~DECAYCD, ~DENS_RED, ~SLA_TOP, ~SLA_BARK, ~SLA_BOLE, ~SLA_STUMP, ~SLA_ROOTS,
 # Hardwoods
 "H", 0, 1, 1, 1, 1, 1, 1,
 "H", 1, 0.970, 1, 0.92, 1, 1, 1, 
 "H", 2, 0.750, 0.50, 0.66, 1, 1, 0.95,
 "H", 3, 0.540, 0.20, 0.39, 1, 1, 0.80,
 "H", 4, 0.613, 0.10, 0.21, 1, 1, 0.65,
 "H", 5, 0.613, 0, 0, 1, 1, 0.50,
 # Softwoods
 "S", 0, 1, 1, 1, 1, 1, 1,
 "S", 1, 0.892, 1, 0.92, 1, 1, 1,
 "S", 2, 0.831, 0.50, 0.66, 1, 1, 0.95,
 "S", 3, 0.591, 0.20, 0.39, 1, 1, 0.80,
 "S", 4, 0.433, 0.10, 0.21, 1, 1, 0.65,
 "S", 5, 0.433, 0, 0, 1, 1, 0.50
 )
```

```{r}
# Sound volume

tree <- tree |> 
  rowwise() |> 
  mutate(VOLCFSND = calc_VOLCFSND(VOLCFGRS = VOLCFGRS, PCT_ROTTEN = CULL)) 
tree$VOLCFGRS
tree$VOLCFSND
```

```{r}
tree <- inner_join(tree, ref_spp, by = "SPCD") 

tree <- inner_join(tree, dead, by = c("SFTWD_HRDWD", "DECAYCD")) |> 
  select(-c(HABTYPCD1, HABTYPCD2))

tree <- tree |> 
  rowwise() |> 
  # 3. DRYBIO_BOLE
  mutate(DRYBIO_BOLE = calc_DRYBIO_BOLE(SPCD = SPCD, VOLCFSND = VOLCFSND, 
                                        WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                                        BARK_VOL_PCT = BARK_VOL_PCT,
                                        BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                                        DENS_RED = DENS_RED, 
                                        SLA_BOLE = SLA_BOLE, 
                                        SLA_BARK = SLA_BARK),
      # 4. CRM adjustment factor   
      CRM_AF = calc_CRM_ADJ(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                               DRYBIO_BOLE = DRYBIO_BOLE, 
                               DBH = DIA),
      # 5. Stump volume and biomass
      DRYBIO_STUMP = calc_DRYBIO_STUMP(SPCD = SPCD, 
                               DBH = DIA,
                               CRM_AF = CRM_AF,
                               RAILE_STUMP_DOB_B1 = RAILE_STUMP_DOB_B1, 
                               RAILE_STUMP_DIB_B1 = RAILE_STUMP_DIB_B1, 
                               RAILE_STUMP_DIB_B2 = RAILE_STUMP_DIB_B2,
                               WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                               BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                               SLA_STUMP = SLA_STUMP),
      # 6. Top and branch biomass
      DRYBIO_TOP = calc_TOP_BRANCH(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                                        DBH = DIA, 
                                        DRYBIO_STUMP = DRYBIO_STUMP, 
                                        DRYBIO_BOLE = DRYBIO_BOLE,
                                      SLA_TOP = SLA_TOP),
      # 7. Total aboveground biomass
      BIOMASS = calc_BIOMASS(DBH = DIA,
                             JENKINS_SPGRPCD =JENKINS_SPGRPCD,
                             DRYBIO_BOLE = DRYBIO_BOLE, 
                                DRYBIO_STUMP = DRYBIO_STUMP, 
                                DRYBIO_TOP = DRYBIO_TOP,
                             DENS_RED = DENS_RED, 
                             SLA_TOP = SLA_TOP, 
                             SLA_BOLE = SLA_BOLE, 
                             SLA_BARK = SLA_BARK),
      # 8. Total aboveground carbon
      CARBON = calc_CARBON(BIOMASS = BIOMASS)
      ) 

tree$VOLCFGRS
tree$VOLCFSND
tree$CRM_AF
tree$DRYBIO_BOLE
tree$DRYBIO_STUMP
tree$DRYBIO_TOP
tree$BIOMASS
tree$CARBON
```
