---
title: "Apply CRM - North Central - Prairie States"
author: "Matt Russell"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(knitr)
library(readxl)
```

```{r}
# Set working directory
my_dir <-"C:/Users/matt/Documents/Arbor/Projects/nsvb/analysis/crm_eqns/"
```

```{r}
# Load volume functions
source(purl(paste0(my_dir, "volume/volume_ncps.Rmd"), quiet = T))

# Load CRM functions
source(purl(paste0(my_dir, "crm/crm.Rmd"), quiet = T))
```


```{r}
# Gross volume
coefs_VOLCFGRS <- read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = "NC_coefs_1") |> 
  rename(COEF_TBL_SP = Species)

config_VOLCFGRS <- read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = "NCPS_config") 

coefs_VOLCFGRS <- inner_join(coefs_VOLCFGRS, config_VOLCFGRS, by = "COEF_TBL_SP") |>
  rename(SPCD = SPECIES_NUM) |>
  relocate(SPCD) |> 
  select(-c(COEF_TBL_SP, CONFIG_ID:COEF_TABLE)) 

# Gross volume (SPCD 66, only)
coefs_VOLCFGRS_66 <- read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = "RMRS_coefs_3") |> 
  rename(SPCD = Species) |> 
  filter(SPCD == 66)

# Gross volume (SPCD 122, only)
coefs_VOLCFGRS_122 <- read_excel(paste0(my_dir, "nrs_gtr88/volcfgrs_eqn_coefs.xlsx"), 
                   sheet = "NC_coefs_2") |> 
  rename(SPCD = Species) |> 
  filter(SPCD == 122)

coefs_VOLCFGRS <- bind_rows(coefs_VOLCFGRS, coefs_VOLCFGRS_66, coefs_VOLCFGRS_122)


# Sound volume
coefs_VOLCFSND <- read_excel(paste0(my_dir, "nrs_gtr88/volcfsnd_eq_coefs.xlsx"), 
                   sheet = "Snd_coefs_2") |> 
   rename(COEF_TBL_SP = Species,
          TREECLCD = Treeclcd) |> 
   mutate(TREECLCD = as.numeric(ifelse(TREECLCD == "Other", 4, TREECLCD))) 

config_VOLCFSND <- read_excel(paste0(my_dir, "nrs_gtr88/volcfsnd_eq_coefs.xlsx"), 
                   sheet = "NCCS_config") |> 
  rename(SPCD = SPECIES_NUM)

coefs_VOLCFSND <- inner_join(coefs_VOLCFSND, config_VOLCFSND, by = "COEF_TBL_SP",
                             relationship = "many-to-many")

# Need to add a SPCD = 66 to sound volume coefficients.
# Use coefficients from SPCD 68 (eastern red cedar)
# coefs_VOLCFSND_66 <- coefs_VOLCFSND |> 
#   filter(SPCD == 68) |> 
#   mutate(SPCD = 66)
# 
# coefs_VOLCFSND <- rbind(coefs_VOLCFSND, coefs_VOLCFSND_66)
# Need to add a SPCD = 122 to sound volume coefficients.
# Use coefficients from SPCD 125 (red pine)
# coefs_VOLCFSND_122 <- coefs_VOLCFSND |> 
#   filter(SPCD == 129) |> 
#   mutate(SPCD = 122)
# 
# coefs_VOLCFSND <- rbind(coefs_VOLCFSND, coefs_VOLCFSND_66, coefs_VOLCFSND_122)

# Reference Species table
ref_spp <- read_csv(paste0(my_dir, "nrs_gtr88/REF_SPECIES.csv")) 

# Domke et al. 2011 Standing dead reductions (their Table 2)
dead <- tribble(
 ~SFTWD_HRDWD, ~DECAYCD, ~DENS_RED, ~SLA_TOP, ~SLA_BARK, ~SLA_BOLE, ~SLA_STUMP, ~SLA_ROOTS,
 # Hardwoods
 "H", 0, 1, 1, 1, 1, 1, 1,
 "H", 1, 0.970, 1, 0.92, 1, 1, 1, 
 "H", 2, 0.750, 0.50, 0.66, 1, 1, 0.95,
 "H", 3, 0.540, 0.20, 0.39, 1, 1, 0.80,
 "H", 4, 0.613, 0.10, 0.21, 1, 1, 0.65,
 "H", 5, 0.613, 0, 0, 1, 1, 0.50,
 # Softwoods
 "S", 0, 1, 1, 1, 1, 1, 1,
 "S", 1, 0.892, 1, 0.92, 1, 1, 1,
 "S", 2, 0.831, 0.50, 0.66, 1, 1, 0.95,
 "S", 3, 0.591, 0.20, 0.39, 1, 1, 0.80,
 "S", 4, 0.433, 0.10, 0.21, 1, 1, 0.65,
 "S", 5, 0.433, 0, 0, 1, 1, 0.50
 )
```

```{r}
tree <- sdt_tree

# 1. Gross volume
tree <- tree |> 
  mutate(SPCD = ifelse(SPCD %in% c(6918, 6748), 999, SPCD)) |> 
  inner_join(coefs_VOLCFGRS, by = "SPCD") 

tree_filter <- tree |> 
  filter(is.na(B1))

tree <- tree |> 
  rowwise() |> 
  mutate(VOLCFGRS = ifelse(SPCD == 66, 
                           calc_VOLCFGRS_66(SPCD = SPCD, DRC = DIA, HT = HT, 
                                            B0 = B0, B1 = B1, B2 = B2, B3 = B3),
                           ifelse(SPCD == 122, 
                                  calc_VOLCFGRS_122(SPCD = SPCD, DBH = DIA, HT = HT, 
                                                    B0 = B0, B1 = B1, B2 = B2, B3 = B3, B4 = B4, B5 = B5),
                           calc_VOLCFGRS(SPCD = SPCD, DBH = DIA, SICOND = SICOND, 
                                         B1 = B1, B2 = B2, B3 = B3, B4 = B4)))) |> 
    select(-c(B1:B5, B0))
tree$VOLCFGRS

# 2. Sound volume
tree <- tree |> 
  mutate(TREECLCD = ifelse(is.na(TREECLCD), 4, TREECLCD)) |> 
  inner_join(coefs_VOLCFSND, by = c("SPCD", "TREECLCD")) 

tree_filter <- tree |> 
  filter(is.na(B0))


tree <- tree |> 
  rowwise() |> 
  mutate(VOLCFSND = calc_VOLCFSND(SPCD = SPCD, DBH = DIA, VOLCFGRS = VOLCFGRS, 
                                  TREECLCD = TREECLCD, B1 = B1, 
                                  B2 = B2)) |>
  select(-c(B1, B2))
tree$VOLCFSND
```

```{r}
tree <- inner_join(tree, ref_spp, by = "SPCD") 

tree <- inner_join(tree, dead, by = c("SFTWD_HRDWD", "DECAYCD")) 

tree <- tree |> 
  rowwise() |> 
  # 3. DRYBIO_BOLE
  mutate(DRYBIO_BOLE = calc_DRYBIO_BOLE(SPCD = SPCD, VOLCFSND = VOLCFSND, 
                                        WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                                        BARK_VOL_PCT = BARK_VOL_PCT,
                                        BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                                        DENS_RED = DENS_RED, 
                                        SLA_BOLE = SLA_BOLE, 
                                        SLA_BARK = SLA_BARK),
      # 4. CRM adjustment factor   
      CRM_AF = calc_CRM_ADJ(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                               DRYBIO_BOLE = DRYBIO_BOLE, 
                               DBH = DIA),
      # 5. Stump volume and biomass
      DRYBIO_STUMP = calc_DRYBIO_STUMP(SPCD = SPCD, 
                               DBH = DIA,
                               CRM_AF = CRM_AF,
                               RAILE_STUMP_DOB_B1 = RAILE_STUMP_DOB_B1, 
                               RAILE_STUMP_DIB_B1 = RAILE_STUMP_DIB_B1, 
                               RAILE_STUMP_DIB_B2 = RAILE_STUMP_DIB_B2,
                               WOOD_SPGR_GREENVOL_DRYWT = WOOD_SPGR_GREENVOL_DRYWT, 
                               BARK_SPGR_GREENVOL_DRYWT = BARK_SPGR_GREENVOL_DRYWT,
                               SLA_STUMP = SLA_STUMP),
      # 6. Top and branch biomass
      DRYBIO_TOP = calc_TOP_BRANCH(JENKINS_SPGRPCD = JENKINS_SPGRPCD, 
                                        DBH = DIA, 
                                        DRYBIO_STUMP = DRYBIO_STUMP, 
                                        DRYBIO_BOLE = DRYBIO_BOLE,
                                      SLA_TOP = SLA_TOP),
      # 7. Total aboveground biomass
      BIOMASS = calc_BIOMASS(DBH = DIA,
                             JENKINS_SPGRPCD =JENKINS_SPGRPCD,
                             DRYBIO_BOLE = DRYBIO_BOLE, 
                                DRYBIO_STUMP = DRYBIO_STUMP, 
                                DRYBIO_TOP = DRYBIO_TOP,
                             DENS_RED = DENS_RED,
                             SLA_TOP = SLA_TOP,
                             SLA_BOLE = SLA_BOLE,
                             SLA_BARK = SLA_BARK),
      # 8. Total aboveground carbon
      CARBON = calc_CARBON(BIOMASS = BIOMASS)
      ) 

tree$VOLCFGRS
tree$VOLCFSND
tree$CRM_AF
tree$DRYBIO_BOLE
tree$DRYBIO_STUMP
tree$DRYBIO_TOP
tree$BIOMASS
tree$CARBON
```



